
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources(不修改相关配置默认必须再resources下,否则扫包扫不到)
mybatis:
  typeAliasesPackage: com.rainbow.quartzdemo
  mapperLocations: classpath:com/rainbow/quartzdemo/mapper/*.xml

spring:
  datasource:
    test:
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

    test1:
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:oracle:thin:@172.16.182.18:1521:orcl
      username: policyprint
      password: sinosoft
      driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8083